# Generated by Django 5.1.7 on 2025-05-04 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_follow_profile_following'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='badges/default_badge.png', upload_to='badges/')),
                ('requirement_type', models.CharField(choices=[('publications_count', 'Publications Count'), ('publication_likes', 'Publication Likes'), ('publication_favorites', 'Publication Favorites'), ('forum_replies', 'Forum Replies'), ('followers_count', 'Followers Count'), ('profile_completion', 'Profile Completion'), ('forums_diversity', 'Forums Diversity')], max_length=100)),
                ('requirement_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='equipped_badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_by', to='accounts.badge'),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0)),
                ('is_equipped', models.BooleanField(default=False)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
