# Generated by Django 5.1.7 on 2025-05-01 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_reply_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
