# Generated by Django 5.1.7 on 2025-05-04 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_topic_dislikes_topic_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solved_topic', to='discussions.reply'),
        ),
    ]
