# Generated by Django 5.1.7 on 2025-05-01 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_likes_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_publications', to=settings.AUTH_USER_MODEL),
        ),
    ]
