# Generated by Django 5.1.7 on 2025-05-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('favorite', 'Favorite'), ('reply', 'Reply'), ('follow', 'Follow'), ('solution', 'Solution')], max_length=20),
        ),
    ]
